wandb_version: 1

learning_rate:
  desc: null
  value: 0.0005
architecture:
  desc: null
  value: MSE
model:
  desc: null
  value: resnet18-pretrained - fe
dataset:
  desc: null
  value: afad
epochs:
  desc: null
  value: 45
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716980042
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
