wandb_version: 1

learning_rate:
  desc: null
  value: 0.0005
architecture:
  desc: null
  value: MSE
model:
  desc: null
  value: resnet50 6 descongelats - DA 0.5% 0-fc1
dataset:
  desc: null
  value: cacd
epochs:
  desc: null
  value: 45
pretrain:
  desc: null
  value: basic IMAGENET
dropout:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717242732
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
